# Generated by Django 5.2.5 on 2025-08-28 12:37

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="deadline",
            field=models.DateField(default=courses.models.default_deadline),
        ),
    ]
