# Generated by Django 5.2.5 on 2025-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_homework_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
