# Generated by Django 5.2.5 on 2025-08-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_homework_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade",
                to="courses.submission",
            ),
        ),
    ]
