# Generated by Django 5.2.5 on 2025-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_grade_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
