# Generated by Django 5.2.5 on 2025-09-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="lecture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework",
                to="courses.lecture",
            ),
        ),
    ]
