version: "3.9"

services:
  web:
    build: .
    container_name: student-management-web
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=management_system.settings
      # DATABASE_URL можно оставить для Django, если используешь dj-database-url
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: student-management-db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
